bas_project/bas_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from users import views


auth_urls = [
    path(
        'auth/registration/',
        views.register, name='registration',
    ),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dictionary.urls', namespace='dictionary')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
] + auth_urls + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bas_project/dictionary/urls.py
from django.urls import path
from . import views  # Импорт ваших views


app_name = 'dictionary'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.term_search, name='term_search'),
    path('legal/', views.legal, name='legal'),
    path('supply-chain/', views.supply_chain, name='supply_chain'),
    path('terms/dpas/', views.term_dpas, name='term_dpas'),
    path('terms/<int:term_id>/add-to-favorites/', views.add_to_favorites, name='add_to_favorites'),
]

bas_project/users/urls.py
from django.urls import include, path

from . import views

app_name = 'users'

profile_urls = [
    path('edit/', views.edit_profile, name='edit_profile'),
    path('<slug:username>/', views.profile, name='profile'),
    ]

urlpatterns = [
    path('profile/', include(profile_urls)),
]

bas_project/templates/includes/footer.html
<footer class="site-footer">
    <div class="container">
        <div class="footer-content">
            <div class="footer-section">
                <h3>О проекте</h3>
                <p>Термины в области беспилотных авиационных систем.</p>
            </div>
            
            <div class="footer-section">
                <h3>Быстрые ссылки</h3>
                <ul class="footer-links">
                    <li><a href="/">Главная страница</a></li>
                    <li><a href="/terms/dpas">Определение</a></li>
                    <li><a href="/legal">Организации</a></li>
                    <li><a href="/supply-chain">Поставки</a></li>
                </ul>
            </div>
            
            <div class="footer-section">
                <h3>Контакты</h3>
                <ul class="footer-contacts">
                    <li>Email: goool@mail.gol</li>
                    <li>Телефон: +7 (495) 500-00-00</li>
                    <li>Telegram: VK YouTube</li>
                </ul>
            </div>
        </div>
        
        <div class="footer-bottom">
            <p>&copy; 2025 Все права защищены.</p>
        </div>
    </div>
</footer>

bas_project/templates/includes/header.html
{% load static %}
<header>
    <div class="container">
        <div class="header-top">
            <div class="header-left">
                <nav>
                    <ul class="nav-menu">
                        <li><a href="/">Главная страница</a></li>
                        <li><a href="/terms/dpas">Определение</a></li>
                        <li><a href="/legal">Организации</a></li>
                        <li><a href="/supply-chain">Поставки</a></li>
                    </ul>
                </nav>
            </div>
            <div class="header-right">
                <!-- Кнопка скачать мобильную версию -->
                <a href="#" class="btn-download">
                    <i class="fas fa-mobile-alt"></i> Скачать приложение
                </a>
                {% with request.resolver_match.view_name as view_name %}
                    {% if user.is_authenticated %}
                        <div class = "profile-buttons">
                        <a href = "{% url 'users:profile' user.username %}" class="btn-profile">
                            Профиль
                        </a>
                        <a href="{% url 'logout' %}?next={% url 'dictionary:home' %}" class="btn-logout">
                            Выйти
                        </a>
                        </div>
                        
                    {% else %}
                        <div class="auth-buttons">
                        <a href="{% url 'login' %}" class="btn-login">Войти</a>
                        <a href="{% url 'registration' %}" class="btn-register">Регистрация</a>
                        </div>
                    {% endif %}
                    </div>
                {% endwith %}
        
                <!-- Выбор языка -->
                <div class="language-selector">
                    <div class="selected-language">RU</div>
                    <div class="language-options">
                        <div class="language-option" data-value="ru">RU</div>
                        <div class="language-option" data-value="en">Eng</div>
                    </div>
                </div>
                <script src="{% static 'js/language-selector.js' %}"></script>
            </div>
        </div>
    </div>
</header>

<!-- Подключение стилей -->
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">